const assert=require('node:assert/strict');
const {chromium}=require(process.env.PATHLY_PLAYWRIGHT_MODULE||'playwright');
const base=process.env.PATHLY_BASE_URL||'http://localhost:5175';
(async()=>{const browser=await chromium.launch({channel:'msedge'});try{
 const page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base+'/stories');
 const records=[{id:'profile',kind:'profile',version:1,updated:new Date().toISOString(),data:{title:'Jamie',setupComplete:'true'}},{id:'task',kind:'task',version:1,updated:new Date().toISOString(),data:{title:'Review program notes',status:'To do'}}];
 await page.evaluate(records=>new Promise((resolve,reject)=>{const req=indexedDB.open('pathly-personal-workspace-v1',1);req.onupgradeneeded=()=>req.result.createObjectStore('workspace');req.onerror=()=>reject(req.error);req.onsuccess=()=>{const db=req.result,tx=db.transaction('workspace','readwrite');tx.objectStore('workspace').put({records,hasCompletedOnboarding:true},'current');tx.oncomplete=()=>{db.close();resolve()}}}),records);
 // Latency and failure exist only in this test harness, never in app code.
 await page.addInitScript(()=>{
  window.__writeDelay=0;window.__readDelay=2200;window.__failWrite=false;
  const transact=IDBDatabase.prototype.transaction,put=IDBObjectStore.prototype.put;
  IDBDatabase.prototype.transaction=function(...args){const tx=transact.apply(this,args),delay=args[1]==='readwrite'?window.__writeDelay:window.__readDelay;
   if(delay)Object.defineProperty(tx,'oncomplete',{configurable:true,set(fn){tx.addEventListener('complete',event=>setTimeout(()=>fn.call(tx,event),delay))}});
   return tx;
  };
  IDBObjectStore.prototype.put=function(...args){if(window.__failWrite){window.__failWrite=false;throw new DOMException('Injected quota failure','QuotaExceededError')}return put.apply(this,args)};
 });
 await page.goto(base+'/app');
 await page.getByText('Reading saved records…',{exact:true}).waitFor();
 assert(await page.getByRole('navigation',{name:'Workspace',exact:true}).isVisible());
 await page.getByRole('button',{name:'Schools',exact:true}).click();
 assert.equal(await page.locator('.header-page-context').innerText(),'Schools');
 assert.equal(await page.locator('.account-loading,[data-slot=dialog-overlay]').count(),0);
 await page.getByRole('heading',{name:'Start with one program you’re curious about.'}).waitFor();
 await page.evaluate(()=>{window.__readDelay=0;window.__writeDelay=3500});
 await page.getByRole('button',{name:'Experiences',exact:true}).click();
 await page.getByRole('button',{name:'Add experience',exact:true}).first().click();
 await page.getByLabel('Experience name').fill('Community clinical volunteering');
 await page.getByLabel('Total documented hours').fill('12');
 await page.getByRole('button',{name:'Save experience',exact:true}).click();
 await page.locator('.editor').waitFor({state:'hidden'});
 assert.equal(await page.locator('[data-slot=dialog-overlay]').count(),0);
 await page.getByRole('heading',{name:'Community clinical volunteering'}).waitFor();
 assert(await page.getByText('Saving changes…',{exact:true}).isVisible());
 await page.screenshot({path:'work/instant-saving-desktop.png'});
 await page.getByRole('button',{name:'Schools',exact:true}).click();
 assert.equal(await page.locator('.header-page-context').innerText(),'Schools');
 await page.getByRole('button',{name:'Experiences',exact:true}).click();
 await page.getByText('Saving changes…',{exact:true}).waitFor({state:'hidden'});
 assert.equal(await page.locator('[data-sonner-toast]').count(),0);
 await page.evaluate(()=>{window.__writeDelay=0;window.__failWrite=true});
 await page.getByRole('button',{name:'Edit Community clinical volunteering',exact:true}).click();
 await page.getByLabel('Total documented hours').fill('24');
 await page.getByRole('button',{name:'Save experience',exact:true}).click();
 await page.locator('.save-recovery').waitFor();
 assert((await page.locator('.record-card').innerText()).includes('12 hours'));
 await page.getByRole('button',{name:'Goals',exact:true}).click();
 assert(await page.locator('.save-recovery').isVisible());
 await page.getByRole('button',{name:'Review draft',exact:true}).click();
 assert.equal(await page.getByLabel('Total documented hours').inputValue(),'24');
 await page.getByRole('button',{name:'Save experience',exact:true}).click();
 await page.locator('.save-recovery').waitFor({state:'hidden'});
 await page.getByRole('button',{name:'Experiences',exact:true}).click();
 assert((await page.locator('.record-card').innerText()).includes('24 hours'));
 await page.reload();await page.getByRole('heading',{name:'Community clinical volunteering'}).waitFor();
 assert((await page.locator('.record-card').innerText()).includes('24 hours'));
 await page.evaluate(()=>{window.__readDelay=0;window.__failWrite=true});
 await page.getByRole('button',{name:'Application',exact:true}).click();
 await page.getByRole('tab',{name:'Tasks & deadlines',exact:true}).click();
 await page.getByRole('checkbox',{name:'Complete Review program notes'}).click();
 await page.locator('.save-recovery').waitFor();
 assert.equal(await page.getByRole('checkbox',{name:'Complete Review program notes'}).isChecked(),false);
 await page.getByRole('button',{name:'Try again',exact:true}).click();
 await page.locator('.save-recovery').waitFor({state:'hidden'});
 assert.equal(await page.getByRole('checkbox',{name:'Complete Review program notes'}).isChecked(),true);
 await page.getByRole('button',{name:'Home',exact:true}).click();
 await page.screenshot({path:'work/instant-workspace-desktop.png'});
 await page.setViewportSize({width:390,height:844});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
 await page.screenshot({path:'work/instant-workspace-mobile.png'});
 await page.setViewportSize({width:1440,height:900});
 await page.evaluate(()=>{window.__writeDelay=1200});
 await page.locator('button.profile').click();
 await page.getByRole('menuitem',{name:'Your Pathly plan',exact:true}).click();
 await page.getByRole('button',{name:'Pre-Nursing',exact:true}).click();
 await page.getByRole('button',{name:'Finish later',exact:true}).click();
 await page.locator('.assessment-dialog').waitFor({state:'hidden'});
 await page.getByRole('button',{name:'Schools',exact:true}).click();
 await page.waitForFunction(()=>new Promise(resolve=>{const req=indexedDB.open('pathly-personal-workspace-v1',1);req.onsuccess=()=>{const db=req.result,tx=db.transaction('workspace','readonly'),read=tx.objectStore('workspace').get('current');read.onsuccess=()=>resolve(read.result.records.find(r=>r.kind==='profile').data.setupDeferred==='true');tx.oncomplete=()=>db.close()}}));
 assert.deepEqual(errors,[]);
 console.log('PASS delayed startup retains shell/navigation; optimistic save navigable during write; no success overlay/toast; failure rolls back and preserves draft across navigation; retry persists after refresh; failed task toggle rolls back; mobile no overflow');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
