const fs=require('fs'),ts=require('typescript'),assert=require('node:assert/strict');require.extensions['.ts']=(m,p)=>m._compile(ts.transpileModule(fs.readFileSync(p,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,p);
const P=require('../app/personalization.ts'),{getNextBestActions}=require('../app/dashboard-state.ts'),{buildPathlyContext}=require('../app/assistant-context.ts'),{answerFromRecords}=require('../app/assistant-service.ts'),{goalProgress}=require('../app/journey.ts'),{meaningfulMilestone}=require('../app/milestone-logic.ts');
const entry=(id,kind,data)=>({id,kind,data,version:1,updated:new Date().toISOString()});
const base={profession:'MD/DO',academicStage:'Junior',year:String(new Date().getFullYear()+2),started:['Clinical experience','Volunteering'],concern:'What should I do next?',goals:['clinical','research','exam'],capacity:'5–10 hours',success:['Reach a clinical-hours goal','Gain research experience'],clinicalTarget:'500',commitment:"I'm committed",completed:true};const profile=p=>entry('p','profile',{title:'Morgan',...P.profileData(p),onboardingCompleted:'true'});
const a=[profile(base)],b=[profile({...base,profession:'PA',academicStage:'Sophomore',year:'',started:[],goals:['clinical','shadowing','gpa'],capacity:'2–5 hours',clinicalTarget:'',success:[],concern:'Am I doing enough?'})],c=[profile({...base,profession:'Dental',academicStage:'Senior',year:String(new Date().getFullYear()),goals:['exam','schools'],started:['Clinical experience','Research','Volunteering'],concern:'Which schools should I be considering?'})];
assert.equal(getNextBestActions(a)[0].id,'profile-research');assert.equal(getNextBestActions(b).length,2);assert(getNextBestActions(c)[0].title.includes('schools'));assert(P.goalLabel('exam',P.readProfile(c[0])).includes('DAT'));assert(P.goalLabel('exam',P.readProfile(a[0])).includes('MCAT'));
assert(answerFromRecords('Why is research a priority?',buildPathlyContext(a)).text.includes('because you selected'));assert(answerFromRecords('What should I do next?',buildPathlyContext(b)).text.includes('haven’t set an application year'));assert(answerFromRecords('What schools should I research?',buildPathlyContext(c)).text.includes('can’t recommend specific schools'));
assert(P.validateAssessment({currentGoals:'["clinical","exam","letters","gpa"]'}));assert(P.validateAssessment({weeklyCapacity:'1000 hours'}));assert(P.validateAssessment({clinicalTarget:'-2'}));assert.equal(P.validateAssessment(P.profileData(base)),null);assert.equal(P.readProfile(undefined).year,'');assert.deepEqual(P.readProfile(entry('x','profile',{currentGoals:'invalid'})).goals,[]);
const suggestion=P.suggestedGoals(a).find(g=>g.key==='clinical'),goal=entry('goal','goal',suggestion.destination.data),exp=entry('exp','experience',{title:'Clinic',category:'Clinical Experience',hours:'312'});assert.equal(goalProgress(goal,[...a,goal,exp]).current,312);assert.equal(P.targetProgress([...a,exp]).current,312);assert(!P.suggestedGoals([...a,goal]).some(g=>g.key==='clinical'));assert(meaningfulMilestone(a,[...a,goal],goal).title.includes('Goal created'));const complete={...exp,data:{...exp.data,hours:'500'}};assert(meaningfulMilestone([...a,goal,exp],[...a,goal,complete],complete));assert.equal(meaningfulMilestone([...a,goal,complete],[...a,goal,complete],complete),null);
const proposed=answerFromRecords('I want 500 clinical hours',buildPathlyContext([...a,exp]));assert.equal(proposed.actions[0].destination.data.total,'500');assert(proposed.text.includes('188'));assert.equal(a.length,1);const unsupported=answerFromRecords('Tell me my admission chance',buildPathlyContext(a));assert(unsupported.text.includes('not a connected language model'));assert(!unsupported.text.includes('78%'));
console.log('PASS three distinct profiles, partial/invalid profiles, deterministic priorities, capacity limits, exam language, suggested-goal acceptance, live category targets, milestone crossing and factual planning actions');

const {recommendActions}=require('../app/recommendations.ts');const priorityGoal={...goal,data:{...goal.data,priority:'High'}};assert(recommendActions([...a,priorityGoal,exp]).find(r=>r.id==='goal-'+goal.id).evidence.includes('312 / 500'));assert(answerFromRecords('I want 999999 clinical hours',buildPathlyContext(a)).text.length>0);
