const fs=require('fs'),ts=require('typescript'),assert=require('node:assert/strict');
require.extensions['.ts']=(m,p)=>m._compile(ts.transpileModule(fs.readFileSync(p,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,p);
const {getSchoolEvidence,hasRequirementSource}=require('../app/school-evidence.ts');
const {sendAskPathlyMessage}=require('../app/copilot-context.ts');
const {getPlanningStatus,changesSince}=require('../app/planning-status.ts');
const {readProfile}=require('../app/personalization.ts');
const {hoursUpdate}=require('../app/experience-hours.ts');
const {getDashboardState}=require('../app/dashboard-state.ts');
const {goalProgress}=require('../app/goal-progress.ts');
const now=new Date(),r=(id,kind,data)=>({id,kind,data,version:1,updated:now.toISOString()});
const school=r('s','school',{title:'Saved program'}),experience=r('e','experience',{title:'Clinic',category:'Clinical Experience',hours:'12'});
const required=(id,status,type='Hard requirement')=>r(id,'requirement',{title:id,school:'s',type,status,category:'Prerequisite'});
const records=[school,experience,required('Biology','Not reviewed'),required('Chemistry','Missing'),required('Lab','In progress'),required('Statistics','Missing','Recommendation'),required('Physics','Not reviewed','')];
const facts=getSchoolEvidence(school,records);assert.equal(facts.missing.length,1);assert.equal(facts.unknown.length,1);assert.equal(facts.inProgress.length,1);assert.equal(facts.recommendations.length,1);assert.equal(facts.unclassified.length,1);
assert(!hasRequirementSource(required('No source','Complete')));assert(!hasRequirementSource(r('x','requirement',{source:'javascript:alert(1)',verified:'2026-01-01'})));assert(!hasRequirementSource(r('x','requirement',{source:'https://example.edu',verified:'2026-02-30'})));
const crowded=[...records,...Array.from({length:8},(_,i)=>r('t'+i,'task',{title:'Urgent '+i,target:now.toISOString().slice(0,10)}))];
assert(getDashboardState(crowded,now).actions.every(a=>a.id.startsWith('task-')));
const answer=sendAskPathlyMessage('Which saved schools am I missing prerequisites for?',crowded,'Home');assert(answer.text.includes('Chemistry'));assert(answer.text.includes('not reviewed'));assert(answer.actions.some(a=>a.destination.record?.id==='Chemistry'));
assert(sendAskPathlyMessage('Which experiences need stronger reflections?',crowded,'Home').actions.some(a=>a.destination.data?.experience==='e'));
assert(sendAskPathlyMessage('Am I on track for my application timeline?',crowded,'Home').text.includes('not enough'));
const updated=hoursUpdate(experience,'8.25');assert.equal(updated.data.hours,'20.25');assert.equal(experience.data.hours,'12');assert.equal(updated.version,1);
for(const value of ['', '0','-1','Infinity','abc'])assert.equal(hoursUpdate(experience,value),null);
const goal=r('g','goal',{title:'My clinical goal',progressSource:'Category hours',category:'Clinical Experience',total:'30',unit:'hours'});
assert.equal(goalProgress(goal,[updated,goal]).current,20.25);assert.equal(getDashboardState([updated],now).hours,20.25);
const reflection=r('ref','reflection',{title:'Lesson',experience:'e',content:'I learned to listen.',status:'Complete',hoursAtReflection:'20.25'});
assert(!getDashboardState([updated,reflection],now).actions.some(a=>a.id==='reflection-e'));
assert(getPlanningStatus(records,now).title.includes('1 required item'));
assert.equal(readProfile(r('p','profile',{pathway:'Pre-PA',education:'Second year'})).profession,'PA');assert.equal(readProfile(r('p','profile',{education:'Second year'})).academicStage,'Sophomore');
assert.equal(changesSince(records,'invalid',now).length,0);assert.equal(changesSince(records,new Date(now.getTime()-1000).toISOString(),now).length,records.length);
console.log('PASS unknown vs missing requirements, topic guidance beyond Home action limit, factual timeline, legacy profile, hour-to-goal-to-dashboard loop, reflection resolution and visit boundaries');
