'use client';
import {useEffect,useRef,useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import type {Entry} from './model';
import type {Destination} from './journey';
import type {AssistantMessage} from './assistant-types';
import {buildPathlyContext} from './assistant-context';
import {answerFromRecords} from './assistant-service';
import {loadConversation,saveConversation} from './browser-workspace';
const prompts=['What should I focus on next?','Am I on track for my application year?','Why is research one of my priorities?','Help me plan this semester.'];
export default function AskPathly({records,onClose,onAction}:{records:Entry[];onClose:()=>void;onAction:(d:Destination)=>void}){
 const [messages,setMessages]=useState<AssistantMessage[]>([]),[input,setInput]=useState(''),[pending,setPending]=useState(false),[loading,setLoading]=useState(true),[loadFailed,setLoadFailed]=useState(false),[error,setError]=useState('');const busy=useRef(false),end=useRef<HTMLDivElement>(null);
 useEffect(()=>{let active=true;loadConversation().then(rows=>{if(active)setMessages(rows)}).catch(()=>{if(active){setLoadFailed(true);setError('Your saved conversation could not be opened. Close and try again.')}}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);
 useEffect(()=>{end.current?.scrollIntoView({block:'nearest'})},[messages.length]);
 async function ask(question:string){if(busy.current||loading||loadFailed||!question.trim())return;busy.current=true;setPending(true);setError('');try{const text=question.trim().slice(0,1500),answer=answerFromRecords(text,buildPathlyContext(records));const next=[...messages,{id:crypto.randomUUID(),role:'user' as const,text,createdAt:new Date().toISOString()},{id:crypto.randomUUID(),role:'assistant' as const,text:answer.text,actions:answer.actions,createdAt:new Date().toISOString()}].slice(-30);await saveConversation(next);setMessages(next);setInput('')}catch{setError('This conversation could not be saved. Your question is still here; please try again.')}finally{busy.current=false;setPending(false)}}
 return <Dialog open onOpenChange={v=>{if(!v&&!pending)onClose()}}><DialogContent className="ask-dialog"><DialogTitle>Ask Pathly</DialogTitle><DialogDescription>Planning guide · Uses your saved Pathly information. No language model is connected and nothing is sent to an AI provider.</DialogDescription><div className="ask-conversation" role="log" aria-label="Ask Pathly conversation" aria-live="polite" aria-busy={pending||loading||loadFailed}>{loading?<p>Opening your conversation…</p>:messages.length?messages.map(m=><article key={m.id} className={'ask-message '+m.role}><h3>{m.role==='user'?'You':'Pathly · from your records'}</h3><p>{m.text}</p>{m.actions?.map((a,i)=><button className="secondary" key={i} disabled={pending} onClick={()=>{onClose();onAction(a.destination)}}>{a.label}</button>)}</article>):<div className="ask-starters"><h3>A useful starting point</h3><p>Ask about your plan, progress, experiences, or next step.</p>{prompts.map(p=><button key={p} disabled={loading||loadFailed||pending} onClick={()=>{setInput(p);void ask(p)}}>{p}</button>)}</div>}<div ref={end}/></div>{error&&<p role="alert" className="error">{error}</p>}<form className="ask-composer" onSubmit={e=>{e.preventDefault();void ask(input)}}><label className="field"><span>Your question</span><textarea value={input} onChange={e=>setInput(e.target.value)} maxLength={1500} rows={2} placeholder="What deserves my attention next?" disabled={pending||loading||loadFailed}/></label><button className="primary" disabled={pending||loading||loadFailed||!input.trim()}>{pending?'Saving…':'Ask Pathly'}</button></form><small>Suggestions are planning guidance. Review and save any proposed change yourself. Recent messages stay in this browser.</small></DialogContent></Dialog>
}
