'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Sparkles} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {loadConversation,saveConversation} from './browser-workspace';
import {getCopilotContext,sendAskPathlyMessage,explainRecommendation,resolveCopilotAction} from './copilot-context';
import {CopilotHeader,CopilotSuggestions,CopilotResponse,CopilotComposer} from './copilot-parts';
import type {Entry} from './model';
import type {Destination,NextAction} from './journey';
import type {AssistantMessage,AssistantAnswer} from './assistant-types';
export type CopilotRequest={id:number;action?:NextAction};
export default function AskPathlyCopilot({records,page,request,onAction,suspended=false}:{records:Entry[];page:string;request:CopilotRequest|null;onAction:(d:Destination)=>void;suspended?:boolean}){
 const [open,setOpen]=useState(false),[messages,setMessages]=useState<AssistantMessage[]>([]),[draft,setDraft]=useState(''),[loading,setLoading]=useState(true),[pending,setPending]=useState(false),[error,setError]=useState(''),[failed,setFailed]=useState(false),[confirm,setConfirm]=useState(false),[mobile,setMobile]=useState(false),[viewport,setViewport]=useState({height:0,bottom:0});
 const busy=useRef(false),handled=useRef<number|null>(null),launcher=useRef<HTMLButtonElement>(null),scroll=useRef<HTMLDivElement>(null);const context=getCopilotContext(page);
 useEffect(()=>{let active=true;loadConversation().then(rows=>{if(active){setMessages(rows);try{setOpen(localStorage.getItem('pathly-copilot-open')==='true')}catch{}}}).catch(()=>{if(active){setFailed(true);setError('Your conversation could not be opened. Refresh to try again.')}}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);
 useEffect(()=>{const media=matchMedia('(max-width: 640px)');const update=()=>{setMobile(media.matches);const v=window.visualViewport;setViewport({height:v?.height||innerHeight,bottom:v?Math.max(0,innerHeight-v.height-v.offsetTop):0})};update();media.addEventListener('change',update);window.visualViewport?.addEventListener('resize',update);return()=>{media.removeEventListener('change',update);window.visualViewport?.removeEventListener('resize',update)}},[]);
 useEffect(()=>{const el=scroll.current;if(el)el.scrollTop=el.scrollHeight},[messages.length,open,pending]);
 function changeOpen(value:boolean){setOpen(value);try{localStorage.setItem('pathly-copilot-open',String(value))}catch{}}
 const append=useCallback(async (question:string,answer:AssistantAnswer)=>{if(busy.current||loading||failed)return;busy.current=true;setPending(true);setError('');try{const stamp=new Date().toISOString(),next=[...messages,{id:crypto.randomUUID(),role:'user' as const,text:question,createdAt:stamp},{id:crypto.randomUUID(),role:'assistant' as const,text:answer.text,actions:answer.actions,createdAt:stamp}].slice(-30);await saveConversation(next);setMessages(next);setDraft('')}catch{setError('Your message could not be saved. Please try again.')}finally{busy.current=false;setPending(false)}},[messages,loading,failed]);
 useEffect(()=>{if(!request||handled.current===request.id||loading||pending||failed)return;handled.current=request.id;void Promise.resolve().then(()=>{changeOpen(true);if(request.action)void append('Why this? '+request.action.title,explainRecommendation(request.action))})},[request,loading,pending,failed,append]); // Requests carry an immutable, selected recommendation snapshot.
 function send(question=draft){const text=question.trim();if(!text||busy.current||loading||failed)return;setDraft(text);void append(text,sendAskPathlyMessage(text,records,page))}
 async function clear(){if(busy.current)return;busy.current=true;setPending(true);setError('');try{await saveConversation([]);setMessages([]);setDraft('');setConfirm(false)}catch{setError('The conversation could not be cleared. Your saved messages are unchanged.')}finally{busy.current=false;setPending(false)}}
 const disabled=loading||pending||failed;
 return <div className="copilot-root"><button ref={launcher} className="copilot-launcher" hidden={open||suspended} aria-label="Open Ask Pathly" aria-expanded={open} aria-controls="pathly-copilot" onClick={()=>changeOpen(true)}><Sparkles size={17}/>Ask Pathly</button><Dialog modal={mobile} open={open&&!suspended} onOpenChange={changeOpen}><DialogContent id="pathly-copilot" className="copilot-panel pathly-light" showCloseButton={false} style={mobile&&viewport.height?{height:viewport.height-16,bottom:viewport.bottom+8}:undefined} onInteractOutside={e=>{if(!mobile)e.preventDefault()}} onCloseAutoFocus={e=>{e.preventDefault();if(!suspended)launcher.current?.focus()}}><CopilotHeader onMinimize={()=>changeOpen(false)} onNew={()=>void clear()} onClear={()=>setConfirm(true)} disabled={disabled}/><div className="copilot-context">Context · {context.label}</div><div className="copilot-scroll" ref={scroll} role="log" aria-label="Ask Pathly conversation" aria-live="polite" aria-busy={disabled}>{loading?<p role="status">Opening your conversation…</p>:messages.length?messages.map(m=><CopilotResponse key={m.id} message={m} disabled={pending} onAction={d=>{const current=resolveCopilotAction(d,records);if(!current){setError('This entry is no longer in your workspace. Ask for a fresh next step.');return}changeOpen(false);onAction(current)}}/>):<CopilotSuggestions prompts={context.prompts} onSend={send} disabled={disabled}/>} {pending&&<p role="status" className="copilot-saving">Saving your conversation…</p>}</div>{error&&<p role="alert" className="error">{error}</p>}<CopilotComposer draft={draft} onChange={setDraft} onSend={()=>send()} disabled={disabled} pending={pending}/><p className="copilot-disclosure">Local planning guide · No AI provider connected.<br/>Recent messages stay in this browser.</p></DialogContent></Dialog><Dialog open={confirm} onOpenChange={v=>{if(!pending)setConfirm(v)}}><DialogContent><DialogTitle>Clear this conversation?</DialogTitle><DialogDescription>This will remove the messages in this Ask Pathly conversation. Your experiences, schools, goals, plan, and profile will not be affected.</DialogDescription><div className="copilot-confirm-actions"><button className="secondary" disabled={pending} onClick={()=>setConfirm(false)}>Cancel</button><button className="primary" disabled={pending} onClick={()=>void clear()}>{pending?'Clearing…':'Clear conversation'}</button></div>{error&&<p role="alert">{error}</p>}</DialogContent></Dialog></div>
}
