'use client';
import {useRef,useState} from 'react';
import {Plus,ArrowUpRight,Inbox} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {Choice} from './editor';
import type {Entry} from './model';
import type {Destination} from './journey';
import {taskComplete,taskStatus,recordDestination,unorganizedCaptures} from './record-links';
import {formatRelativeDate} from './product-intelligence';

export function TaskList({records,onAction,onSave,demo=false,title='Tasks & deadlines'}:{records:Entry[];onAction:(d:Destination)=>void;onSave:(r:Entry)=>Promise<void>;demo?:boolean;title?:string}) {
  const [pending,setPending]=useState<string[]>([]),[error,setError]=useState('');
  const inFlight=useRef(new Set<string>());
  const tasks=records.filter(r=>r.kind==='task').sort((a,b)=>Number(taskComplete(a))-Number(taskComplete(b))||(a.data.target||'9999').localeCompare(b.data.target||'9999'));
  async function toggle(entry:Entry){if(inFlight.current.has(entry.id))return;inFlight.current.add(entry.id);setPending(old=>[...old,entry.id]);setError('');try{const done=!taskComplete(entry);await onSave({...entry,data:{...entry.data,status:done?'Completed':'To do',complete:String(done)}})}catch{setError('This task was not updated. Please try again.')}finally{inFlight.current.delete(entry.id);setPending(old=>old.filter(id=>id!==entry.id));}}
  return <section className="connected-tasks"><div className="section-heading"><h2>{title}</h2><button className="inline-action" onClick={()=>onAction({page:'Application',tab:'tasks',kind:'task'})}>Add task<Plus size={15}/></button></div>{error&&<p className="error" role="alert">{error}</p>}{tasks.length?<ul>{tasks.map(task=><li key={task.id}><Checkbox aria-label={'Complete '+task.data.title} checked={taskComplete(task)} disabled={demo||pending.includes(task.id)} onCheckedChange={()=>void toggle(task)}/><button onClick={()=>onAction(recordDestination(task,true))}><strong>{task.data.title}</strong><span>{taskStatus(task)}{task.data.target?' · '+formatRelativeDate(task.data.target):''}{task.data.category?' · '+task.data.category:''}</span></button><ArrowUpRight size={14}/></li>)}</ul>:<p className="empty-inline">A deadline, a recommendation request, or one next step. Add only what you need to remember.</p>}</section>;
}

export function QuickCapture({onClose,onSave,onInbox}:{onClose:()=>void;onSave:(r:Entry)=>Promise<void>;onInbox:()=>void}) {
  const [text,setText]=useState(''),[type,setType]=useState(''),[date,setDate]=useState(''),[saving,setSaving]=useState(false),[error,setError]=useState(''),[discard,setDiscard]=useState(false);const busy=useRef(false);
  function close(){if(saving)return;if(text.trim())setDiscard(true);else onClose()}
  async function submit(event:React.FormEvent){event.preventDefault();if(busy.current||!text.trim())return;busy.current=true;setSaving(true);setError('');try{await onSave({id:crypto.randomUUID(),kind:'capture',version:0,updated:'',data:{title:text.trim().slice(0,100),content:text.trim(),type,date}});onClose();}catch{setError('Your thought was not saved. Keep it here and try again.');}finally{busy.current=false;setSaving(false)}}
  return <><Dialog open onOpenChange={open=>{if(!open)close()}}><DialogContent className="quick-capture"><DialogTitle>Capture a thought</DialogTitle><DialogDescription>Save the thought now. Organize it later.</DialogDescription><form onSubmit={submit}><label className="field"><span>What would you like to remember?</span><textarea autoFocus required maxLength={20000} rows={5} value={text} onChange={e=>setText(e.target.value)} placeholder="A useful detail, a moment, or something to follow up on…"/></label><details className="more-fields"><summary>Optional details</summary><div className="form-grid"><label className="field"><span>Type</span><Choice value={type} onChange={setType} label="Capture type" options={['Experience','Reflection','Story Moment','Task','Goal','School Note'].map(value=>({value,label:value}))}/></label><label className="field"><span>Date</span><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label></div></details><p className="form-hint">Leave out patient names and identifying details.</p>{error&&<p className="error" role="alert">{error}</p>}<div className="form-actions"><button type="button" className="secondary" disabled={saving} onClick={close}>Cancel</button><button className="primary" disabled={saving||!text.trim()}>{saving?'Saving…':'Save thought'}</button></div></form><button className="inline-action" disabled={saving||!!text.trim()} onClick={onInbox}>Open saved thoughts<ArrowUpRight size={14}/></button></DialogContent></Dialog><AlertDialog open={discard} onOpenChange={setDiscard}><AlertDialogContent><AlertDialogTitle>Discard this unsaved thought?</AlertDialogTitle><AlertDialogDescription>You can keep writing or discard this draft.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Keep writing</AlertDialogCancel><AlertDialogAction onClick={onClose}>Discard thought</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></>;
}

const captureKinds=[['experience','Experience'],['reflection','Reflection'],['story','Story Moment'],['task','Task'],['goal','Goal'],['schoolNote','School Note']];
export function CaptureInbox({records,onAction,onCapture}:{records:Entry[];onAction:(d:Destination)=>void;onCapture:()=>void}) {
  const [kinds,setKinds]=useState<Record<string,string>>({});const captures=unorganizedCaptures(records);
  function organize(capture:Entry){const kind=kinds[capture.id]||'story';const data:Record<string,string>={title:capture.data.title,capture:capture.id,date:capture.data.date||'',status:['story','reflection'].includes(kind)?'Draft':kind==='task'?'To do':''};data[kind==='story'?'happened':['reflection','schoolNote'].includes(kind)?'content':kind==='task'?'notes':'description']=capture.data.content||capture.data.title;onAction({...recordDestination({...capture,kind}),record:undefined,kind,data});}
  return <section className="capture-inbox"><div className="section-heading"><div><h2>Saved thoughts</h2><p className="subtle">The original stays connected when you organize a thought.</p></div><button className="secondary" onClick={onCapture}><Plus size={15}/>Capture</button></div>{captures.length?<ul>{captures.map(capture=><li key={capture.id}><p>{capture.data.content||capture.data.title}</p><small>Saved {formatRelativeDate(capture.updated)}</small><div className="capture-organize"><Choice value={kinds[capture.id]||'story'} onChange={v=>setKinds(old=>({...old,[capture.id]:v}))} label={'Organize '+capture.data.title+' as'} options={captureKinds.map(([value,label])=>({value,label}))}/><button className="secondary" onClick={()=>organize(capture)}>Organize<ArrowUpRight size={14}/></button><button className="text-button" onClick={()=>onAction(recordDestination(capture,true))}>Edit</button></div></li>)}</ul>:<div className="empty-state"><Inbox size={25}/><h3>A place for details you don’t want to lose.</h3><p>Save a thought now. Decide where it belongs when you have a moment.</p><button className="primary" onClick={onCapture}>Capture a thought</button></div>}</section>;
}
