'use client';
import {ArrowUp,ArrowUpRight,Minus,MoreHorizontal,Sparkles} from 'lucide-react';
import {DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuItem} from '@/components/ui/dropdown-menu';
import type {AssistantMessage} from './assistant-types';
import type {Destination} from './journey';
export function CopilotHeader({onMinimize,onNew,onClear,disabled}:{onMinimize:()=>void;onNew:()=>void;onClear:()=>void;disabled:boolean}){return <header className="copilot-header"><div><DialogTitle><Sparkles size={18} aria-hidden/>Ask Pathly</DialogTitle><DialogDescription>Your planning copilot</DialogDescription></div><div className="copilot-controls"><button className="icon-button" aria-label="Minimize Ask Pathly" onClick={onMinimize}><Minus size={18}/></button><DropdownMenu><DropdownMenuTrigger asChild><button className="icon-button" aria-label="Conversation options"><MoreHorizontal size={19}/></button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem disabled={disabled} onSelect={onNew}>New conversation</DropdownMenuItem><DropdownMenuItem disabled={disabled} onSelect={onClear}>Clear conversation</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div></header>}
export function CopilotSuggestions({prompts,onSend,disabled}:{prompts:string[];onSend:(p:string)=>void;disabled:boolean}){return <div className="copilot-empty"><span className="copilot-mark"><Sparkles size={22}/></span><h3>What can we figure out together?</h3><p>I can use your experiences, goals, schools, application progress, and Pathly plan to help you decide what comes next.</p><div>{prompts.map(p=><button key={p} disabled={disabled} onClick={()=>onSend(p)}>{p}<ArrowUpRight size={15}/></button>)}</div></div>}
export function CopilotResponse({message,onAction,disabled=false}:{message:AssistantMessage;onAction:(d:Destination)=>void;disabled?:boolean}){return <article className={'copilot-message '+message.role}><h3>{message.role==='user'?'You':'Pathly · from your records'}</h3>{message.text.split('\n\n').map((text,i)=><p key={i}>{text}</p>)}{message.actions?.length?<div className="copilot-actions">{message.actions.map((a,i)=><button key={i} disabled={disabled} onClick={()=>onAction(a.destination)}>{a.label}<ArrowUpRight size={14}/></button>)}</div>:null}</article>}
export function CopilotComposer({draft,onChange,onSend,disabled,pending}:{draft:string;onChange:(s:string)=>void;onSend:()=>void;disabled:boolean;pending:boolean}){return <form className="copilot-composer" onSubmit={e=>{e.preventDefault();onSend()}}><label className="sr-only" htmlFor="copilot-question">Ask Pathly a question</label><textarea id="copilot-question" value={draft} onChange={e=>onChange(e.target.value)} placeholder="Ask about your next step…" maxLength={1500} rows={2} disabled={disabled} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();if(!disabled&&draft.trim())onSend()}}}/><button aria-label={pending?'Saving response':'Send message'} disabled={disabled||!draft.trim()}><ArrowUp size={18}/></button></form>}
