'use client';
import {useEffect,useRef,useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import type {Entry} from './model';
import {professions,academicStages,startedAreas,concerns,capacities,successOptions,commitments,goalKeys,goalLabel,readProfile,profileData,planSummary,type StudentProfile,type GoalKey} from './personalization';
import {SuccessMark} from './milestone';
const questions=['What are you working toward?','Where are you in your journey?','When are you hoping to apply?','What have you already started?','What feels most unclear right now?','What are your biggest goals right now?','How much time can you realistically dedicate each week?','A year from now, what would make you feel on track?','How are you approaching your goal?'];
const descriptions=['Choose the path that fits you today.','Your plan can change as your journey develops.','An estimate is enough. You can update this later.','Select all that apply. These are self-reported starting points, not verified experience records.','We’ll use this to make your next steps clearer.','Choose up to three priorities. These become suggestions, not automatic commitments.','A realistic plan should fit alongside the rest of your life.','Choose what progress means to you. Any hours target is your own, not an admissions requirement.','There is no right answer. This won’t be used to score or rank you.'];
const stages=['Organizing your goals','Reviewing your starting points','Building your next steps','Personalizing your dashboard'];
export default function GuidedSetup({profile,firstName,onSave,onDone}:{profile?:Entry;firstName:string;onSave:(r:Entry)=>Promise<void>;onDone:(kind?:string)=>void}){
 const [answers,setAnswers]=useState(()=>readProfile(profile));
 const [step,setStep]=useState(()=>profile?.data.onboardingCompleted==='true'?0:Math.max(0,Math.min(10,Number(profile?.data.assessmentStep)||0)));
 const [saving,setSaving]=useState(false),[error,setError]=useState(''),[building,setBuilding]=useState(0);
 const working=useRef(profile),busy=useRef(false),heading=useRef<HTMLHeadingElement>(null);
 useEffect(()=>{heading.current?.focus()},[step]);
 useEffect(()=>{if(step!==9)return;const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;const timers=stages.map((_,i)=>setTimeout(()=>setBuilding(i),reduced?0:i*400));const done=setTimeout(()=>setStep(10),reduced?80:1600);return()=>{timers.forEach(clearTimeout);clearTimeout(done)}},[step]);
 async function persist(next:StudentProfile,index:number,extra:Record<string,string>={}){if(busy.current)return false;busy.current=true;setSaving(true);setError('');try{const r:Entry={id:working.current?.id||crypto.randomUUID(),kind:'profile',version:working.current?.version||0,updated:working.current?.updated||'',data:{...working.current?.data,title:working.current?.data.title||firstName,...profileData(next),assessmentStep:String(index),...extra}};await onSave(r);working.current={...r,version:r.version+1};return true}catch(e){setError(e instanceof Error?e.message:'Your answers could not be saved. Please try again.');return false}finally{busy.current=false;setSaving(false)}}
 async function choose(next:StudentProfile){setAnswers(next);await persist(next,step)}
 async function move(next:number){if(await persist(answers,next))setStep(next)}
 async function close(){if(busy.current)return;if(await persist(answers,step,{setupDeferred:'true'}))onDone()}
 async function finish(){if(await persist(answers,0,{onboardingCompleted:'true',onboardingCompletedAt:working.current?.data.onboardingCompletedAt||new Date().toISOString(),setupComplete:'true',setupDeferred:'false',assessmentStep:'0'}))onDone()}
 const currentYear=new Date().getFullYear();
 const single=(key:keyof StudentProfile,options:string[])=>options.map(value=>({id:value,label:value,selected:answers[key]===value,next:{...answers,[key]:value}}));
 const multi=(key:'started'|'goals'|'success',options:string[])=>options.map(value=>{const selected=answers[key] as string[];return {id:value,label:key==='goals'?goalLabel(value as GoalKey,answers):value,selected:selected.includes(value),next:{...answers,[key]:selected.includes(value)?selected.filter(x=>x!==value):[...selected,value]}}});
 const options=step===0?single('profession',professions):step===1?single('academicStage',academicStages):step===2?[...single('year',Array.from({length:5},(_,i)=>String(currentYear+i))),{id:'unsure',label:'Not sure yet',selected:!answers.year,next:{...answers,year:''}}]:step===3?multi('started',startedAreas):step===4?single('concern',concerns):step===5?multi('goals',[...goalKeys]):step===6?single('capacity',capacities):step===7?multi('success',successOptions):single('commitment',commitments);
 const valid=step===0?!!answers.profession:step===1?!!answers.academicStage:step===4?!!answers.concern:step===6?!!answers.capacity:step===8?!!answers.commitment:true;
 return <Dialog open onOpenChange={open=>{if(!open)void close()}}><DialogContent className="assessment-dialog" showCloseButton={false} onEscapeKeyDown={e=>{if(saving)e.preventDefault()}}>
 {step<9?<><div className="assessment-kicker"><span>Your Pathly plan</span><span>{step+1} of 9</span></div><div className="assessment-progress" role="progressbar" aria-label="Assessment progress" aria-valuenow={step+1} aria-valuemin={0} aria-valuemax={9}><span style={{width:((step+1)/9*100)+'%'}}/></div><DialogTitle ref={heading} tabIndex={-1}>{questions[step]}</DialogTitle><DialogDescription>{descriptions[step]}</DialogDescription><div className="assessment-options" role="group" aria-label={questions[step]} key={step}>{options.map(option=><button key={option.id} type="button" aria-pressed={option.selected} disabled={saving||step===5&&!option.selected&&answers.goals.length>=3} onClick={()=>void choose(option.next)}>{option.label}<span aria-hidden="true">{option.selected?'✓':'+'}</span></button>)}</div>{step===7&&answers.success.includes(successOptions[0])&&<label className="field"><span>Clinical-hours target (optional)</span><input type="number" min="1" max="100000" value={answers.clinicalTarget} onChange={e=>setAnswers({...answers,clinicalTarget:e.target.value})} onBlur={()=>void persist(answers,step)} placeholder="Your own target"/></label>}<div className="assessment-actions"><button className="text-button" disabled={saving} onClick={()=>void close()}>Finish later</button><div>{step>0&&<button className="secondary" disabled={saving} onClick={()=>void move(step-1)}>Back</button>}<button className="primary" disabled={saving||!valid} onClick={()=>void move(step+1)}>{saving?'Saving…':step===8?'See my plan':'Continue'}</button></div></div></>:step===9?<div className="plan-building"><DialogTitle>Building your Pathly plan</DialogTitle><DialogDescription>Turning what you told us into a starting plan.</DialogDescription><div className="assessment-progress"><span style={{width:((building+1)/4*100)+'%'}}/></div><p role="status" aria-live="polite">{stages[building]}</p><button className="text-button" onClick={()=>void close()}>Finish later</button></div>:<div className="plan-payoff"><SuccessMark/><DialogTitle ref={heading} tabIndex={-1}>Your Pathly plan is ready.</DialogTitle><DialogDescription>{planSummary(answers)}</DialogDescription><p>Pathly will help you track experiences, preserve your story, and decide what deserves your attention next.</p><dl><div><dt>Current focus</dt><dd>{answers.goals[0]?goalLabel(answers.goals[0],answers):'Explore your next step'}</dd></div><div><dt>Target cycle</dt><dd>{answers.year||'Still exploring'}</dd></div><div><dt>Weekly capacity</dt><dd>{answers.capacity||'Not set'}</dd></div></dl><div className="assessment-actions"><button className="text-button" disabled={saving} onClick={()=>void move(8)}>Back</button><button className="primary" disabled={saving} onClick={()=>void finish()}>{saving?'Saving your plan…':'Build My Path'}</button></div><button className="text-button" disabled={saving} onClick={()=>void close()}>Finish later</button></div>}
 {error&&<p className="error" role="alert">{error}</p>}
 </DialogContent></Dialog>
}
