'use client';
import {useRef,useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Choice} from './editor';
import type {Entry} from './model';

export default function GuidedSetup({profile,firstName,onSave,onDone}:{profile?:Entry;firstName:string;onSave:(r:Entry)=>Promise<void>;onDone:(kind?:string)=>void}) {
  const [step,setStep]=useState(0),[path,setPath]=useState(profile?.data.pathway||''),[stage,setStage]=useState(profile?.data.stage||''),[year,setYear]=useState(profile?.data.applicationYear||''),[error,setError]=useState(''),[saving,setSaving]=useState(false);const busy=useRef(false);
  async function finish(kind?:string){if(busy.current)return;busy.current=true;setSaving(true);setError('');try{await onSave({id:profile?.id||crypto.randomUUID(),kind:'profile',version:profile?.version||0,updated:profile?.updated||'',data:{...profile?.data,title:profile?.data.title||firstName,pathway:path,stage,applicationYear:year,setupComplete:'true',recap:profile?.data.recap||'true'}});const result=await fetch('/api/preferences',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({hasCompletedOnboarding:true,outcome:'completed'})});if(!result.ok)throw new Error();onDone(kind);}catch{setError('We couldn’t finish saving your setup. Close for now or try again from Profile & preferences.');}finally{busy.current=false;setSaving(false)}}
  return <Dialog open onOpenChange={open=>{if(!open&&!saving)void finish()}}><DialogContent className="guided-setup" showCloseButton={false}><DialogTitle>{step===0?'Let’s make Pathly yours.':step===1?'Where are you now?':'Start with one useful thing.'}</DialogTitle><DialogDescription>{step===0?'A few details will help organize the workspace around where you are now.':step===1?'A rough plan is enough. You can change it at any time.':'Add something you’ve done or a program you’re considering. You can also explore first.'}</DialogDescription><span className="subtle">{step+1} of 3 · Optional setup</span>{step===0&&<label className="field"><span>Your path</span><Choice label="Your path" value={path} onChange={setPath} options={['Pre-pharmacy','Pre-medical','Pre-dental','Pre-PA','Other'].map(value=>({value,label:value}))}/></label>}{step===1&&<div className="form-grid"><label className="field"><span>Current stage</span><Choice label="Current stage" value={stage} onChange={setStage} options={['Exploring','Building experience','Preparing to apply','Applying now'].map(value=>({value,label:value}))}/></label><label className="field"><span>Expected application year</span><input inputMode="numeric" pattern="[0-9]{4}" maxLength={4} value={year} onChange={e=>setYear(e.target.value.replace(/\D/g,''))} placeholder="Optional"/></label></div>}{step===2&&<div className="setup-choices"><button className="primary" disabled={saving} onClick={()=>void finish('experience')}>Add an experience</button><button className="secondary" disabled={saving} onClick={()=>void finish('school')}>Add a school</button></div>}{error&&<p className="error" role="alert">{error}<button onClick={()=>onDone()}>Close for now</button></p>}<div className="form-actions"><button className="text-button" disabled={saving} onClick={()=>void finish()}>Skip setup</button>{step>0&&<button className="secondary" disabled={saving} onClick={()=>setStep(step-1)}>Back</button>}{step<2?<button className="primary" disabled={saving||!!year&&year.length!==4} onClick={()=>setStep(step+1)}>Next</button>:<button className="secondary" disabled={saving} onClick={()=>void finish()}>{saving?'Saving…':'Explore Home'}</button>}</div></DialogContent></Dialog>;
}
