'use client';
import {useEffect,useMemo,useState} from 'react';
import {PlanContext,PersonalTarget} from './personalized-home';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {getStudentContext,studentGreeting} from './student-context';
import {formatRelativeDate} from './product-intelligence';
import {recordDestination} from './record-links';
import {ArrowUpRight,Plus,ArrowRight,BookOpen,Clock} from 'lucide-react';
import type {Entry} from './model';
import {dateLabel,type Destination} from './journey';
import {getDashboardState,type QuickAction} from './dashboard-state';
type State=ReturnType<typeof getDashboardState>;
type Navigate=(destination:Destination)=>void;
export function HomeHeader({name,subtitle,demo,onExample,onAction,newUser}:{name:string;subtitle:string;demo:boolean;newUser:boolean;onExample:()=>void;onAction:Navigate}) {return <header className="heading home-heading"><div><span className="eyebrow">YOUR PATH, MADE CLEAR</span><h1 tabIndex={-1}>{name}</h1><p>{demo?'An example journey with fictional records. Your own data stays separate.':subtitle}</p></div><div className="home-header-actions"><button className={newUser?'secondary':'primary'} onClick={()=>onAction({page:'Experiences',kind:'experience'})}><Plus size={16}/>Add experience</button><button className="text-button" onClick={onExample}>{demo?'Open my journey':'Explore example'}<ArrowUpRight size={14}/></button></div></header>}
export function QuickActions({actions,onAction}:{actions:QuickAction[];onAction:Navigate}) {return <nav className="home-quick" aria-label="Quick actions"><span>Quick actions</span>{actions.map(action=><button key={action.label} onClick={()=>onAction(action.destination)}>{action.label}<ArrowUpRight size={14}/></button>)}</nav>}
export function NextBestActions({state,demo,onAction}:{state:State;demo:boolean;onAction:Navigate}) {const actions=demo?[]:state.actions;return <section className="home-panel home-priorities"><div className="home-section-title"><h2>Your Next Best Actions</h2><span>What matters now</span></div>{actions.length?<ol>{actions.map((action,i)=><li key={action.id}><span className="home-action-number">{i+1}</span><div><h3>{action.title}</h3><p className="home-evidence">{action.evidence}</p><details><summary>Why this matters</summary><p>{action.reason}</p></details><button className={i===0?'primary':'inline-action'} onClick={()=>onAction(action.destination)}>{action.label}<ArrowUpRight size={14}/></button></div></li>)}</ol>:<div className="home-start"><BookOpen size={24}/><h3>{demo?'Your own journey shapes your priorities.':state.stage==='BRAND_NEW'?'Start with something you’ve already done.':'You’re up to date with your saved plans.'}</h3><p>{demo?'Explore the example workspaces, then add your first experience for personal next steps.':state.stage==='BRAND_NEW'?'Add clinical work, research, volunteering, or another experience. Pathly will connect it to reflections, goals, and your future application.':'No current records trigger a next step. Keep your experiences and school requirements up to date as your plans develop.'}</p><button className="primary" onClick={()=>onAction({page:'Experiences',kind:'experience'})}>Add {state.stage==='BRAND_NEW'?'your first ':''}experience<Plus size={15}/></button></div>}</section>}
export function ReadinessCard({state,onAction}:{state:State;onAction:Navigate}) {const [selected,setSelected]=useState<State['readiness'][number]|null>(null);return <><section className="home-panel home-readiness"><div className="home-section-title"><h2>Application readiness</h2><button aria-label="Review application readiness" onClick={()=>onAction({page:'Application',tab:'readiness'})}><ArrowUpRight size={17}/></button></div><p>What you’ve documented, area by area.</p><div className="home-readiness-grid">{state.readiness.map(area=><button key={area.name} onClick={()=>setSelected(area)}><strong>{area.name}</strong><span className={'home-status '+area.state}>{area.status}</span></button>)}</div><small>Preparation visibility, never an admissions prediction.</small></section>{selected&&<Dialog open onOpenChange={open=>{if(!open)setSelected(null)}}><DialogContent><DialogTitle>{selected.name}</DialogTitle><DialogDescription>{selected.evidence}</DialogDescription><p>{selected.next}</p><p className="subtle">Based only on your recorded information. No admissions prediction.</p><button className="primary" onClick={()=>{onAction(selected.destination);setSelected(null)}}>Review supporting records<ArrowUpRight size={14}/></button></DialogContent></Dialog>}</>}
export function JourneyStats({state,onAction}:{state:State;onAction:Navigate}) {return <section className="home-standing"><div className="home-section-title"><h2>Where you stand</h2><button className="inline-action" onClick={()=>onAction({page:'Experiences',tab:'timeline'})}>Journey<ArrowRight size={14}/></button></div>{state.stage==='BRAND_NEW'?<p>Your experiences and meaningful moments will build a picture of your progress here.</p>:<dl>{[[state.hours.toLocaleString(),'Documented hours'],[state.experiences,'Experiences'],[state.stories,'Story moments']].map(([value,label])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>}</section>}
export function UpcomingItems({state,onAction}:{state:State;onAction:Navigate}) {const items=state.upcoming.filter(item=>item.days>=0).slice(0,4),overdue=state.upcoming.filter(item=>item.days<0);return <section className="home-panel home-horizon"><div className="home-section-title"><h2>On the horizon</h2><Clock size={16}/></div>{items.map(item=><button className="home-upcoming" key={item.entry.id+item.label} onClick={()=>onAction(recordDestination(item.entry,true))}><strong>{item.entry.data.title}</strong><span>{formatRelativeDate(item.date)} · {item.label}</span></button>)}{!!overdue.length&&<details><summary>{overdue.length} past target dates to review</summary>{overdue.slice(0,4).map(item=><button className="home-upcoming" key={item.entry.id+item.label} onClick={()=>onAction(recordDestination(item.entry,true))}><strong>{item.entry.data.title}</strong><span>{dateLabel(item.date)} · {item.label}</span></button>)}</details>}{!items.length&&!overdue.length&&<button className="inline-action" onClick={()=>onAction({page:'Application',tab:'tasks',kind:'task'})}>Add a task or deadline<Plus size={14}/></button>}</section>}
export function WeeklyActivity({state,onAction}:{state:State;onAction:Navigate}) {const active=state.weekly.filter(item=>item.count>0);return <section className="home-panel home-week"><div className="home-section-title"><h2>This week</h2><span>Last 7 days</span></div>{active.length?<><div className="home-week-counts">{active.map(item=><span key={item.kind}><b>{item.count}</b>{item.label}</span>)}</div><small>{state.weekSummary.added.length} new records · {state.weekSummary.completed.length} tasks completed. Counts use saved timestamps.</small></>:<p>No updates in the last seven days. Pick up with one useful next step.</p>}{state.actions[0]&&<button className="weekly-focus inline-action" onClick={()=>onAction(state.actions[0].destination)}>Suggested focus: {state.actions[0].label}<ArrowUpRight size={14}/></button>}{state.recent.length>0&&<details className="recent-activity"><summary>Recently in Pathly</summary>{state.recent.map(item=><button key={item.entry.id} onClick={()=>onAction(recordDestination(item.entry))}><span>{item.label} {item.entry.data.title}</span><small>{item.date}</small></button>)}</details>}</section>}
export function StoryMomentCard({state,onAction}:{state:State;onAction:Navigate}) {return <section className="home-panel home-story"><BookOpen size={19}/><div><h2>What stayed with you?</h2><p>A conversation, a lesson, a new perspective.</p><button className="inline-action" onClick={()=>onAction(state.storyDestination)}>Capture a moment<ArrowUpRight size={14}/></button></div></section>}
export default function HomeDashboard({records,name,demo,recap,onExample,onAction,onSetup,onAsk}:{onSetup:()=>void;onAsk:()=>void;records:Entry[];name:string;demo:boolean;recap:boolean;onExample:()=>void;onAction:Navigate}) {
 const [now,setNow]=useState(()=>new Date());useEffect(()=>{const timer=setInterval(()=>setNow(new Date()),60000);return()=>clearInterval(timer)},[]);
 const state=useMemo(()=>getDashboardState(records,now,name),[records,now,name]);const context=getStudentContext(records,name);
 return <div className="home-dashboard"><HomeHeader newUser={state.stage==='BRAND_NEW'} name={demo?'Example workspace':studentGreeting(context.firstName,now.getHours())} subtitle={state.subtitle} demo={demo} onExample={onExample} onAction={onAction}/>{!demo&&<PlanContext records={records} priority={state.actions[0]?.title} onSetup={onSetup}/>}<QuickActions actions={state.quickActions} onAction={onAction}/><div className="home-grid"><div className="home-main-column"><NextBestActions state={state} demo={demo} onAction={onAction}/>{state.continueItem&&!demo&&<section className="continue-item"><span className="eyebrow">CONTINUE WHERE YOU LEFT OFF</span><button onClick={()=>onAction(state.continueItem!.destination)}><span><strong>{state.continueItem.entry.data.title}</strong><small>{state.continueItem.context}</small></span><ArrowUpRight size={18}/></button></section>}<JourneyStats state={state} onAction={onAction}/>{recap&&<WeeklyActivity state={state} onAction={onAction}/>}</div><div className="home-side-column">{!demo&&<><button className="ask-entry" onClick={onAsk}><strong>Ask Pathly</strong><span>Make sense of your plan, progress and next step.</span><span>Local planning guide · Uses your saved information</span></button><PersonalTarget records={records} onAction={onAction}/></>}<ReadinessCard state={state} onAction={onAction}/><UpcomingItems state={state} onAction={onAction}/>{state.experiences>0&&<StoryMomentCard state={state} onAction={onAction}/>}</div></div></div>
}
