import type {Entry} from './model';
import {taskComplete,letterStatus} from './record-links';
export type Destination={page:string;tab?:string;kind?:string;record?:Entry;edit?:boolean;data?:Record<string,string>};
export type NextAction={id:string;title:string;reason:string;evidence:string;label:string;priority:number;tone:'attention'|'opportunity';destination:Destination};
export type ReadinessArea={name:string;state:'documented'|'attention'|'empty';status:string;evidence:string;next:string;destination:Destination};
const day=86400000;
export function dateLabel(value?:string){if(!value)return 'Date not set';const date=new Date(value.slice(0,10)+'T12:00:00');return Number.isNaN(date.getTime())?'Date not set':date.toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})}
export function daysUntil(value:string,now=new Date()){return Math.ceil((new Date(value+'T23:59:59').getTime()-now.getTime())/day)}
export {goalProgress} from './goal-progress';
export function schoolAlignment(school:Entry,records:Entry[]){const requirements=records.filter(r=>r.kind==='requirement'&&r.data.school===school.id);const hard=requirements.filter(r=>r.data.type==='Hard requirement');const complete=hard.filter(r=>r.data.status==='Complete'||r.data.status==='Not applicable');const missing=hard.filter(r=>!['Complete','Not applicable'].includes(r.data.status));const unverified=requirements.filter(r=>!r.data.verified||!r.data.source);return {requirements,hard,complete,missing,unverified,summary:hard.length?`${complete.length} of ${hard.length} recorded requirements addressed`:'Requirements not documented',status:!requirements.length?'Review requirements':unverified.length?'Verification needed':missing.length?'Preparation needed':complete.length===hard.length&&hard.length?'Recorded requirements addressed':'Review alignment'}}
export {recommendActions as nextActions} from './recommendations';
export function readiness(records:Entry[]):ReadinessArea[]{const of=(kind:string)=>records.filter(r=>r.kind===kind);const reflections=of('reflection').filter(r=>r.data.content?.trim()&&r.data.status!=='Draft');const categories=[['Clinical exposure','Clinical Experience'],['Shadowing','Shadowing'],['Research','Research'],['Service','Community Service'],['Leadership','Leadership']];const result:ReadinessArea[]=categories.map(([name,category])=>{const rows=of('experience').filter(e=>e.data.category===category||(name==='Service'&&e.data.category==='Volunteering'));const hours=rows.reduce((s,e)=>s+Number(e.data.hours||0),0);const reflected=rows.filter(e=>reflections.some(r=>r.data.experience===e.id)).length;return {name,state:!rows.length?'empty':!reflected?'attention':'documented',status:!rows.length?'Not documented':!reflected?'Reflect next':'Developing',evidence:rows.length?`${rows.length} experience${rows.length===1?'':'s'} · ${hours.toLocaleString()} hours · ${reflected} reflected`:'No experiences documented in this area',next:!rows.length?'Consider how this area fits your pathway':!reflected?'Capture what you learned':'Keep recording meaningful details',destination:{page:'Experiences',tab:'experience'}}});
 const reqs=of('requirement').filter(r=>r.data.category==='Prerequisite'||r.data.category==='Test');const academicDone=reqs.filter(r=>['Complete','Not applicable'].includes(r.data.status)).length;const academicUnverified=reqs.filter(r=>!r.data.source||!r.data.verified).length;result.push({name:'Academic preparation',state:!reqs.length?'empty':academicDone<reqs.length||academicUnverified?'attention':'documented',status:!reqs.length?'Not reviewed':academicDone<reqs.length||academicUnverified?'Review gaps':'Documented',evidence:reqs.length?`${academicDone} of ${reqs.length} prerequisites / tests marked complete · ${academicUnverified} need verification`:'Add school-specific prerequisites and testing requirements',next:'Review the sources behind your academic plan',destination:{page:'Schools',tab:'requirement'}});
 const letters=of('letter');result.push({name:'Letters & relationships',state:!letters.length?'empty':letters.every(l=>l.data.agreed!=='true')?'attention':'documented',status:!letters.length?'Not started':letters.some(l=>l.data.agreed==='true')?'Developing':'Plan next steps',evidence:`${letters.length} potential writer${letters.length===1?'':'s'} · ${letters.filter(l=>l.data.agreed==='true').length} agreed`,next:'Nurture relationships and plan requests early',destination:{page:'Application',tab:'letter'}});
 const schools=of('school');const pending=schools.filter(s=>{const a=schoolAlignment(s,records);return !a.requirements.length||a.missing.length||a.unverified.length}).length;result.push({name:'School planning',state:!schools.length?'empty':pending?'attention':'documented',status:!schools.length?'Not started':pending?'Verify & prepare':'Documented',evidence:`${schools.length} saved program${schools.length===1?'':'s'}${pending?' · '+pending+' need review':''}`,next:'Connect each school to a verified preparation plan',destination:{page:'Schools',tab:'school'}});
 const stories=of('story');result.push({name:'Your application story',state:!stories.length&&!reflections.length?'empty':!stories.length?'attention':'documented',status:stories.length?'Taking shape':reflections.length?'Capture a moment':'Not started',evidence:`${stories.length} Story Moments · ${reflections.length} reflections`,next:'Preserve the details before turning them into essays',destination:{page:'Application',tab:'writing'}});
 const tasks=of('task'),done=tasks.filter(taskComplete);result.push({name:'Application preparation',state:!tasks.length?'empty':done.length<tasks.length?'attention':'documented',status:!tasks.length?'Not planned':done.length<tasks.length?'In progress':'Tasks complete',evidence:`${done.length} of ${tasks.length} self-defined tasks complete`,next:'Set practical next steps for your application cycle',destination:{page:'Application',tab:'readiness'}});const essays=of('essay');const drafted=essays.filter(e=>e.data.content?.trim());result.push({name:'Writing & materials',state:!essays.length?'empty':drafted.length<essays.length?'attention':'documented',status:!essays.length?'Not started':drafted.length<essays.length?'Draft next':'Drafts saved',evidence: drafted.length+' of '+essays.length+' writing records contain draft text',next:'Review your writing against each application requirement',destination:{page:'Application',tab:'writing'}});const goals=of('goal');const open=goals.filter(g=>!['Completed','Paused'].includes(g.data.status));result.push({name:'Goals & next steps',state:!goals.length?'empty':open.length?'attention':'documented',status:!goals.length?'Not planned':open.length?'In progress':'Reviewed',evidence:open.length+' active goals · '+goals.filter(g=>g.data.status==='Completed').length+' completed',next:'Review progress and target dates',destination:{page:'Goals'}});return result;
}
export type JourneyEvent={id:string;date:string;title:string;type:string;detail:string;entry:Entry};
export function journeyEvents(records:Entry[]):JourneyEvent[]{const entries:JourneyEvent[]=[];for(const r of records){if(r.kind==='profile')continue;let date='',type='',detail='';if(r.kind==='experience'){date=r.data.start;type=r.data.category||'Experience';detail=r.data.organization||r.data.role||'A new chapter in your experience';}else if(r.kind==='story'||r.kind==='reflection'){date=r.data.date||r.updated;type=r.kind==='story'?'Story Moment':'Reflection';detail=records.find(e=>e.id===r.data.experience)?.data.title||'A perspective worth preserving';}else if(r.kind==='goal'&&r.data.status==='Completed'){date=r.updated;type='Goal completed';detail=r.data.description||'A step forward';}else if(r.kind==='school'){date=r.updated;type='School planning';detail=r.data.status||'Researching';}else if(r.kind==='task'&&r.data.complete==='true'){date=r.updated;type='Preparation complete';detail=r.data.category;}else if(r.kind==='essay'){date=r.updated;type='Application writing';detail=r.data.type;}if(date)entries.push({id:r.id,date,title:r.data.title,type,detail,entry:r})}return entries.sort((a,b)=>b.date.localeCompare(a.date))}
export function upcoming(records:Entry[],now=new Date()){
 const items:{entry:Entry;date:string;days:number;label:string}[]=[];
 for(const entry of records){
  const data=entry.data;
  const add=(date:string,label:string)=>{const days=daysUntil(date,now);if(Number.isFinite(days))items.push({entry,date,days,label});};
  if(entry.kind==='school'&&!['Withdrawn','Rejected','Accepted'].includes(data.status)){if(data.deadline&&!['Submitted','Interview','Waitlisted'].includes(data.status))add(data.deadline,'Application deadline');if(data.interview)add(data.interview,'Interview');}
  if(entry.kind==='goal'&&!['Completed','Paused'].includes(data.status)&&data.target)add(data.target,'Goal');
  if(entry.kind==='task'&&!taskComplete(entry)&&data.target)add(data.target,'Task');
  if(entry.kind==='letter'&&letterStatus(entry)!=='Submitted'&&data.target)add(data.target,'Recommendation');
  if(entry.kind==='essay'&&data.status!=='Complete'&&data.target)add(data.target,'Writing');
  if(entry.kind==='requirement'&&!['Complete','Not applicable'].includes(data.status)&&data.target)add(data.target,'Requirement');
 }
 return items.sort((a,b)=>a.date.localeCompare(b.date)||a.entry.id.localeCompare(b.entry.id));
}
