export type Entry={id:string;kind:string;data:Record<string,string>;version:number;updated:string};
export const categories=['Clinical Experience','Shadowing','Research','Volunteering','Community Service','Leadership','Employment','Teaching / Tutoring','Extracurricular Activities','Advocacy','Awards / Honors','Publications','Presentations','Certifications','Other'];
export const themes=['Patient interaction','Why this profession','Personal motivation','Challenge','Ethical dilemma','Leadership','Empathy','Failure','Growth','Teamwork','Resilience','Ethics','Communication','Healthcare disparities','Cultural awareness','Problem solving','Mentorship','Research curiosity'];
export const preparation=['Experiences','Reflections','Story Moments','Personal Statement','Letters of Recommendation','School List','Prerequisites','Testing','Resume / CV','Application Timeline','Interview Preparation'];
export type Field={key:string;label:string;type?:string;options?:string[];link?:string};
const f=(key:string,label:string,type='text',options?:string[]):Field=>({key,label,type,options});
const link=(key:string,label:string,kind:string):Field=>({key,label,link:kind});
export const fields:Record<string,Field[]>={
experience:[f('title','Experience name'),f('organization','Organization'),f('category','Category','select',categories),f('role','Role / position'),f('start','Start date','date'),f('ongoing','Currently ongoing','check'),f('end','End date','date'),f('hours','Total documented hours','number'),f('description','Description','textarea'),f('location','Location'),f('weekly','Average hours per week','number'),f('supervisor','Supervisor / contact'),f('contact','Contact information'),f('responsibilities','Responsibilities','textarea'),f('impact','Impact and measurable outcomes','textarea'),f('skills','Skills developed'),f('tags','Tags, separated by commas'),f('application','Application relevance','select',['Undecided','Include','Do not include']),f('meaningful','Meaningful experience candidate','check'),f('letterWriter','Potential letter writer','check'),f('applicationDescription','Application description (your original record stays intact)','textarea'),f('characterLimit','Application character limit','number')],
reflection:[f('title','Reflection title'),link('experience','Associated experience','experience'),f('date','Date','date'),f('prompt','Reflection prompt','select',['Free-form reflection','What did you learn?','What surprised you?','What challenged you?','How did this affect your interest in healthcare?','What did you learn about working with others?','What did you learn about patients or communities?','How did your responsibilities change?','What moment do you still remember?','What skills did you develop?','How did your perspective change?']),f('content','Your reflection','textarea'),f('status','Writing status','select',['Draft','Complete'])],
story:[f('title','Story title'),link('experience','Associated experience (optional)','experience'),f('date','Date','date'),f('happened','What happened?','textarea'),f('mattered','Why did it matter?','textarea'),f('learned','What did you learn?','textarea'),f('people','People involved (avoid identifying patient details)'),f('themes','Themes, separated by commas'),f('use','Possible application use'),link('essay','Related essay','essay'),link('reflection','Related reflection','reflection'),f('status','Writing status','select',['Draft','Complete'])],
school:[f('title','School / program name'),f('program','Program type','select',['Medicine','Dentistry','Physician Assistant','Pharmacy','Other']),f('degree','Degree type'),f('location','Location'),f('status','Status','select',['Researching','Interested','Planning to Apply','Applying','Submitted','Interview','Accepted','Waitlisted','Rejected','Withdrawn']),f('deadline','Application deadline','date'),f('website','Official website','url'),f('service','Application service'),f('gpa','Minimum GPA (documented)'),f('recommendedGpa','Recommended GPA'),f('test','Test requirements'),f('score','Minimum test score'),f('clinical','Required clinical hours'),f('shadowing','Shadowing expectations'),f('letters','Letter requirements'),f('residency','Residency preference'),f('mission','Mission / program focus','textarea'),f('tuition','Estimated tuition'),f('length','Program length'),f('classSize','Class size'),f('notes','Notes and prerequisite details','textarea'),f('verified','Last verified against official sources','date'),f('interview','Interview date','date'),f('decision','Decision notes','textarea')],
requirement:[f('title','Requirement or recommendation'),link('school','School','school'),f('type','Classification','select',['Hard requirement','Recommendation']),f('category','Area','select',['Prerequisite','Test','Clinical','Shadowing','Letters','Other']),f('status','Your preparation','select',['Not reviewed','Missing','In progress','Complete','Not applicable']),f('source','Official source URL','url'),f('verified','Date verified','date'),f('notes','Evidence and notes','textarea'),f('target','Review / completion target','date')],
goal:[f('title','Goal title'),f('category','Category','select',categories.concat(['Application','Prerequisites','Testing','School list'])),f('description','Description','textarea'),f('target','Target date','date'),f('status','Status','select',['Not Started','In Progress','Completed','Paused']),f('priority','Priority','select',['Normal','High','Low']),link('experience','Related experience','experience'),link('school','Related school','school'),f('progressSource','Progress source','select',['Manual progress','Linked experience hours']),f('baseline','Starting hours to exclude (for additional-hours goals)','number'),f('current','Current amount (manual progress)','number'),f('total','Target amount','number'),f('unit','Unit (hours, specialties, etc.)'),f('notes','Notes','textarea'),f('area','Preparation area','select',preparation)],
letter:[f('title','Letter writer name'),f('position','Role / title'),f('relationship','Relationship'),f('email','Email (optional)','email'),f('status','Status','select',['Considering','Planning to ask','Requested','Confirmed','Submitted']),f('target','Target date','date'),link('school','Related school','school'),link('experience','Associated experience','experience'),f('organization','Organization'),f('duration','How long have they known you?'),f('programs','Other programs / letter categories'),f('requestedDate','Requested date','date'),f('submittedDate','Submitted date','date'),f('thanks','Thank-you sent','check'),f('notes','Notes','textarea')],
essay:[f('title','Essay title'),f('type','Purpose','select',['Personal statement','Secondary essay','Interview preparation','Scholarship essay','Resume / CV notes']),f('content','Your writing','textarea'),f('limit','Character limit','number'),f('notes','Outline / themes','textarea'),link('school','Related school','school'),f('target','Due date','date'),f('status','Writing status','select',['Draft','Complete']),f('prompt','Supplemental question / prompt','textarea')],
task:[f('title','Task'),f('status','Status','select',['To do','In progress','Completed']),f('priority','Priority','select',['Normal','High','Low']),f('target','Due date','date'),f('category','Preparation area','select',preparation),f('notes','Details','textarea'),link('school','Related school','school'),link('experience','Related experience','experience'),link('goal','Related goal','goal'),link('letter','Related recommender','letter'),link('essay','Related writing','essay'),link('requirement','Related requirement','requirement')],
capture:[f('title','Saved thought'),f('content','Thought','textarea'),f('type','Type (optional)','select',['Experience','Reflection','Story Moment','Task','Goal','School Note']),f('date','Date','date')],
schoolNote:[f('title','Note title'),link('school','School','school'),f('content','Note','textarea')],
profile:[f('title','First name'),f('pathway','Pathway','select',['Pre-medical','Pre-dental','Pre-PA','Pre-pharmacy','Other']),f('education','Current education year','select',['High school','First year','Second year','Third year','Fourth year','Graduate / post-baccalaureate','Gap year','Other']),f('applicationYear','Expected application year'),f('graduation','Graduation year'),f('gpa','GPA (optional)'),f('exam','Standardized exam (optional)'),f('examScore','Exam score (optional)'),f('recap','Show optional weekly recap','check'),f('stage','Current stage','select',['Exploring','Building experience','Preparing to apply','Applying now','Explore','Build Experiences','Reflect','Develop','Plan','Prepare','Apply']),f('fullName','Display name (optional)')]
};
const sample=(id:string,kind:string,data:Record<string,string>):Entry=>({id,kind,data,version:0,updated:'2026-09-21T12:00:00Z'});
export const examples:Entry[]=[
sample('e1','experience',{title:'Emergency Department Volunteer',organization:'Memorial Hospital',category:'Clinical Experience',role:'Volunteer',start:'2024-09-01',ongoing:'true',hours:'186',description:'Help patients and families navigate the emergency department, restock supplies, and support the care team.',impact:'Provided consistent support during weekly evening shifts.',application:'Include',meaningful:'true'}),
sample('e2','experience',{title:'Undergraduate Research Assistant',organization:'Cell Biology Lab',category:'Research',start:'2025-01-15',ongoing:'true',hours:'240',description:'Investigating cellular responses with a faculty-led research team.',letterWriter:'true',application:'Include'}),
sample('e3','experience',{title:'Community Food Bank Volunteer',organization:'Community Food Bank',category:'Community Service',start:'2023-09-01',end:'2024-08-31',hours:'96',description:'Worked with volunteers to prepare and distribute food to local families.',meaningful:'true'}),
sample('e4','experience',{title:'Internal Medicine Shadowing',organization:'Community Clinic',category:'Shadowing',start:'2025-06-01',end:'2025-06-30',hours:'24'}),
sample('e5','experience',{title:'Peer Mentor',organization:'Pre-health Society',category:'Leadership',start:'2025-09-01',ongoing:'true',hours:'60'}),
sample('e6','experience',{title:'Neighborhood Health Fair',organization:'Community Coalition',category:'Community Service',start:'2024-05-01',end:'2024-05-01',hours:'12'}),
sample('e7','experience',{title:'Summer Research Workshop',organization:'Cell Biology Lab',category:'Research',start:'2024-07-01',end:'2024-07-12',hours:'16'}),
sample('e8','experience',{title:'Patient Welcome Volunteer',organization:'Memorial Hospital',category:'Clinical Experience',start:'2024-02-01',end:'2024-03-01',hours:'8'}),
sample('g1','goal',{title:'Explore two shadowing specialties',category:'Shadowing',status:'In Progress',current:'1',total:'2',unit:'specialties',target:'2026-12-15'}),
sample('g2','goal',{title:'Add 50 clinical hours',category:'Clinical Experience',status:'In Progress',current:'32',total:'50',unit:'hours',experience:'e1',target:'2026-12-01'}),
sample('g3','goal',{title:'Reflect on my research experience',status:'Not Started',experience:'e2',target:'2026-10-15'}),
sample('s1','story',{title:'The value of being present',experience:'e1',date:'2026-09-18',happened:'I sat with a patient who was waiting for news.',mattered:'Sometimes the most meaningful thing I could offer was simply being there.',learned:'Presence and listening can matter as much as finding the right words.',themes:'Empathy, Communication',use:'Personal statement'}),
sample('r1','reflection',{title:'Listening before acting',experience:'e1',date:'2026-09-18',content:'I learned to listen before assuming what a patient or family needed. These small conversations deepened my motivation to work in healthcare.'}),
sample('sc1','school',{title:'Lakeside School of Medicine',program:'Medicine',degree:'MD',location:'Midwest',status:'Researching',mission:'Community-centered healthcare',notes:'Fictional example program. Add and verify your own school requirements.'}),
sample('sc2','school',{title:'Valley College of Medicine',program:'Medicine',degree:'DO',location:'Northeast',status:'Interested',notes:'Fictional example program. No actual admissions requirements are represented.'}),
sample('l1','letter',{title:'Dr. Morgan Chen',position:'Research advisor',organization:'Cell Biology Lab',experience:'e2',relationship:'Faculty mentor',duration:'18 months',strength:'Strong'}),
sample('t1','task',{title:'Document current experiences',category:'Experiences',complete:'true'}),sample('t2','task',{title:'Create a first school shortlist',category:'School List',complete:'true'}),sample('t3','task',{title:'Outline my personal statement',category:'Personal Statement',complete:'false'})];

// Illustrative requirements belong only to the clearly labeled, fictional example journey.
examples.push(
 sample('rq1','requirement',{title:'General Chemistry I',school:'sc1',type:'Hard requirement',category:'Prerequisite',status:'Complete',notes:'Illustrative requirement for a fictional school. No real program requirement is represented.'}),
 sample('rq2','requirement',{title:'Organic Chemistry II',school:'sc1',type:'Hard requirement',category:'Prerequisite',status:'Missing',notes:'Illustrative planning gap. Verify actual prerequisites for any real program you add.'}),
 sample('rq3','requirement',{title:'Faculty letter of recommendation',school:'sc2',type:'Hard requirement',category:'Letters',status:'In progress',notes:'Illustrative only. Add an official source when recording a real school requirement.'})
);
