import type {Entry} from './model';
import type {NextAction,Destination} from './journey';
export const professions=['MD/DO','PA','Nursing','Dental','Pharmacy','Other'];
export const academicStages=['Freshman','Sophomore','Junior','Senior','Gap year','Post-bacc','Other'];
export const startedAreas=['Clinical experience','Research','Volunteering','Shadowing','Leadership','Letters of recommendation','Entrance exam preparation','School research'];
export const concerns=['Am I doing enough?','What should I do next?','Which schools should I be considering?','How do I keep track of everything?','How do I build a strong application story?'];
export const capacities=['Less than 2 hours','2–5 hours','5–10 hours','10+ hours'];
export const successOptions=['Reach a clinical-hours goal','Gain research experience','Complete my entrance exam','Improve my GPA','Secure strong letters','Complete meaningful shadowing','Build a balanced school list','Feel confident about my application','Other'];
export const commitments=["I'm exploring","I'm committed","I'm going all in"];
export const goalKeys=['clinical','research','gpa','shadowing','exam','letters','service','schools','leadership','timeline'] as const;
export type GoalKey=typeof goalKeys[number];
export type StudentProfile={profession:string;academicStage:string;year:string;started:string[];concern:string;goals:GoalKey[];capacity:string;success:string[];clinicalTarget:string;commitment:string;completed:boolean};
function list(value?:string):string[]{try{const v:unknown=JSON.parse(value||'[]');return Array.isArray(v)?v.filter((x):x is string=>typeof x==='string'):[]}catch{return []}}
const one=(value:string|undefined,options:string[])=>options.includes(value||'')?value! :'';
export function readProfile(entry?:Entry):StudentProfile{const d=entry?.data||{};return {profession:one(d.targetProfession,professions),academicStage:one(d.academicStage,academicStages),year:/^\d{4}$/.test(d.applicationYear||'')?d.applicationYear:'',started:list(d.completedAreas).filter(x=>startedAreas.includes(x)),concern:one(d.primaryConcern,concerns),goals:list(d.currentGoals).filter((x):x is GoalKey=>goalKeys.includes(x as GoalKey)).slice(0,3),capacity:one(d.weeklyCapacity,capacities),success:list(d.oneYearSuccessGoals).filter(x=>successOptions.includes(x)),clinicalTarget:Number(d.clinicalTarget)>0&&Number(d.clinicalTarget)<=100000?d.clinicalTarget:'',commitment:one(d.commitmentLevel,commitments),completed:d.onboardingCompleted==='true'};}
export function validateAssessment(d:Record<string,string>):string|null{for(const [key,options] of [['targetProfession',professions],['academicStage',academicStages],['primaryConcern',concerns],['weeklyCapacity',capacities],['commitmentLevel',commitments]] as const)if(d[key]&&!options.includes(d[key]))return 'Choose an available profile option.';for(const [key,options,max] of [['completedAreas',startedAreas,8],['currentGoals',[...goalKeys],3],['oneYearSuccessGoals',successOptions,9]] as const){if(!d[key])continue;try{const v:unknown=JSON.parse(d[key]);if(!Array.isArray(v)||v.length>max||new Set(v).size!==v.length||v.some(x=>typeof x!=='string'||!(options as readonly string[]).includes(x)))return 'Review your selected profile answers.'}catch{return 'Your profile selections could not be read.'}}if(d.clinicalTarget&&(!Number.isFinite(Number(d.clinicalTarget))||Number(d.clinicalTarget)<=0||Number(d.clinicalTarget)>100000))return 'Enter a positive hours target up to 100,000.';return null;}
export function profileData(p:StudentProfile){const pathway:Record<string,string>={'MD/DO':'Pre-medical',PA:'Pre-PA',Nursing:'Pre-nursing',Dental:'Pre-dental',Pharmacy:'Pre-pharmacy',Other:'Other'};return {targetProfession:p.profession,pathway:pathway[p.profession]||'',academicStage:p.academicStage,education:({Freshman:'First year',Sophomore:'Second year',Junior:'Third year',Senior:'Fourth year','Gap year':'Gap year','Post-bacc':'Graduate / post-baccalaureate',Other:'Other'} as Record<string,string>)[p.academicStage]||'',stage:p.year&&Number(p.year)<=new Date().getFullYear()+1?'Preparing to apply':'Building experience',applicationYear:p.year,completedAreas:JSON.stringify(p.started),primaryConcern:p.concern,currentGoals:JSON.stringify(p.goals),weeklyCapacity:p.capacity,oneYearSuccessGoals:JSON.stringify(p.success),clinicalTarget:p.clinicalTarget,commitmentLevel:p.commitment};}
export function examLabel(p:StudentProfile){return p.profession==='MD/DO'?'MCAT':p.profession==='Dental'?'DAT':p.profession==='Pharmacy'?'Program-specific testing review':'Entrance exam preparation'}
export function goalLabel(key:GoalKey,p:StudentProfile){return {clinical:p.profession==='PA'?'Build patient-care experience':p.profession==='Pharmacy'?'Build pharmacy-related experience':'Build clinical experience',research:'Start or grow research experience',gpa:'Work toward your GPA goal',shadowing:p.profession==='Dental'?'Find dental shadowing opportunities':'Find shadowing opportunities',exam:p.profession==='Pharmacy'?examLabel(p):'Prepare for '+examLabel(p),letters:'Build relationships for letters',service:'Increase volunteering',schools:'Research schools',leadership:'Strengthen leadership experience',timeline:'Organize your application timeline'}[key]}
export function categoryFor(key:GoalKey){return {clinical:'Clinical Experience',research:'Research',gpa:'Prerequisites',shadowing:'Shadowing',exam:'Testing',letters:'Application',service:'Volunteering',schools:'School list',leadership:'Leadership',timeline:'Application'}[key]}
export function suggestedGoals(records:Entry[],now=new Date()){const p=readProfile(records.find(r=>r.kind==='profile'));return p.goals.filter(key=>!records.some(r=>r.kind==='goal'&&r.data.suggestionKey===key)).map(key=>{const measurable=key==='clinical'&&p.clinicalTarget;const date=new Date(now);date.setFullYear(date.getFullYear()+1);return {key,title:measurable?`Reach ${p.clinicalTarget} clinical hours`:goalLabel(key,p),destination:{page:'Goals',kind:'goal',data:{title:measurable?`Reach ${p.clinicalTarget} clinical hours`:goalLabel(key,p),suggestionKey:key,category:categoryFor(key),status:'Not Started',priority:'Normal',description:`A goal you selected in your Pathly plan.${p.capacity?' Weekly capacity: '+p.capacity+'.':''}`,...(measurable?{total:p.clinicalTarget,unit:'hours',progressSource:'Category hours',target:date.toISOString().slice(0,10)}:{})}} satisfies Destination}})}
export function profileActions(records:Entry[],now=new Date()):NextAction[]{const p=readProfile(records.find(r=>r.kind==='profile'));if(!p.completed)return [];const result:NextAction[]=[];const suggestions=suggestedGoals(records,now);for(const [i,g] of suggestions.entries()){let priority=72-i;if(g.key==='research'&&!p.started.includes('Research')&&p.started.includes('Clinical experience'))priority+=6; if(g.key==='schools'&&p.concern===concerns[2])priority+=6;if(['schools','exam','timeline','letters'].includes(g.key)&&p.year&&Number(p.year)<=now.getFullYear()+1)priority+=4;const started=p.started.includes(g.key==='clinical'?'Clinical experience':g.key==='research'?'Research':g.key==='service'?'Volunteering':g.key==='shadowing'?'Shadowing':'');result.push({id:'profile-'+g.key,title:g.title,reason:'This is one of your chosen goals, not an admissions requirement. Start with a manageable step and adjust it as your plans change.',evidence:`You selected this priority${started?' and said you have started in this area':''}.${p.capacity?' Your weekly capacity: '+p.capacity+'.':''}`,label:'Review suggested goal',priority,tone:'opportunity',destination:g.destination});}
const map:Record<string,string>={'Clinical experience':'Clinical Experience',Research:'Research',Volunteering:'Volunteering',Shadowing:'Shadowing',Leadership:'Leadership'};for(const area of p.started){const category=map[area];if(category&&!records.some(r=>r.kind==='experience'&&r.data.category===category))result.push({id:'document-'+category,title:`Add your ${area.toLowerCase()} to Pathly`,reason:'You said you have started this area. Recording the details gives your plan evidence to work with.',evidence:'Reported in your assessment · No matching experience recorded yet',label:'Add experience',priority:69,tone:'opportunity',destination:{page:'Experiences',kind:'experience',data:{category}}});}
return result.sort((a,b)=>b.priority-a.priority||a.id.localeCompare(b.id));}
export function targetProgress(records:Entry[]){const p=readProfile(records.find(r=>r.kind==='profile'));if(!p.clinicalTarget)return null;const current=records.filter(r=>r.kind==='experience'&&r.data.category==='Clinical Experience').reduce((n,r)=>n+Math.max(0,Number(r.data.hours)||0),0);return {current,total:Number(p.clinicalTarget),percent:Math.min(100,100*current/Number(p.clinicalTarget))};}
export function planSummary(p:StudentProfile){return [`You’re ${p.profession?'working toward '+p.profession:'exploring your professional path'}${p.year?', with '+p.year+' as your target application year':', with your application timeline still open'}.`,p.started.length?'You said you’ve started '+p.started.slice(0,3).join(', ').toLowerCase()+'.':'You can build your experience record at your own pace.',p.goals.length?'Your current focus: '+p.goals.map(k=>goalLabel(k,p)).join('; ')+'.':'Your priorities can evolve as you learn more.'].join(' ')}
