'use client';
import {useState} from 'react';
import type {PlanningMemory} from './student-intelligence';
import {updatePlanningMemory} from './browser-workspace';
export function PlanningMemoryPanel({memories,onChange,candidate}:{memories:PlanningMemory[];onChange:(rows:PlanningMemory[])=>void;candidate?:string}){
 const [editing,setEditing]=useState(''),[text,setText]=useState(candidate||''),[pending,setPending]=useState(false),[error,setError]=useState('');
 async function save(id:string,value:string|null){setPending(true);setError('');try{onChange(await updatePlanningMemory(id,value));setEditing('');setText('');}catch(e){setError(e instanceof Error?e.message:'This decision could not be saved. Your text is still here.');}finally{setPending(false);}}
 return <details className="planning-memory" open={candidate?true:undefined}><summary>Planning decisions · {memories.length} of 8</summary><p>Only decisions you save here become planning memory. Keep sensitive details out. These stay in this browser and remain separate from chat history.</p>{memories.map(m=><div key={m.id}><p>{m.text}</p><button type="button" className="text-button" disabled={pending} onClick={()=>{setEditing(m.id);setText(m.text)}}>Edit decision</button><button type="button" className="text-button" disabled={pending} onClick={()=>void save(m.id,null)}>Remove decision</button></div>)}<form onSubmit={e=>{e.preventDefault();if(!pending&&text.trim())void save(editing||crypto.randomUUID(),text)}}><label className="field"><span>{candidate?'Review suggested decision':'A decision to remember'}</span><textarea maxLength={240} rows={2} value={text} onChange={e=>setText(e.target.value)} placeholder="I want to focus on one research opportunity this semester."/></label><button className="secondary" disabled={pending||!text.trim()||!editing&&memories.length>=8}>{pending?'Saving…':editing?'Save decision changes':'Save this decision'}</button>{error&&<p role="alert" className="error">{error}</p>}</form></details>;
}
