'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,Sparkles} from 'lucide-react';
import {demoAnswers,type ProductView} from './demo-data';
export default function AskPathlyDemo({onExplore}:{onExplore:(view:ProductView)=>void}){
 const [selected,setSelected]=useState(0),[busy,setBusy]=useState(false);const timer=useRef<ReturnType<typeof setTimeout>|null>(null);const answer=demoAnswers[selected];
 useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current)},[]);
 function choose(index:number){if(timer.current)clearTimeout(timer.current);setSelected(index);if(matchMedia('(prefers-reduced-motion: reduce)').matches){setBusy(false);return}setBusy(true);timer.current=setTimeout(()=>setBusy(false),360)}
 return <section id="ask-pathly" className="company-section ask-demo" aria-labelledby="ask-demo-heading"><div className="ask-demo-intro"><span className="eyebrow">ASK PATHLY</span><h2 id="ask-demo-heading">Your journey has context.<br/><em>Ask it a question.</em></h2><p>Connect the experiences, goals, schools, and application work you’ve organized. Understand your progress—and decide what deserves attention next.</p><div className="demo-prompt-list" role="group" aria-label="Example questions">{demoAnswers.map((a,i)=><button key={a.id} aria-pressed={selected===i} onClick={()=>choose(i)}>{a.question}<ArrowUpRight size={15}/></button>)}</div><small>Try an example question. Then explore your own journey in Pathly.</small></div><div className="ask-demo-panel" data-testid="ask-pathly-demo"><header><div><Sparkles size={20}/><span><strong>Ask Pathly</strong><small>Your planning copilot</small></span></div><span className="demo-label">Illustrative journey</span></header><div className="demo-grounding"><span>Grounded in this Pathly journey</span><div aria-label="Relevant example context">{answer.context.map(label=><span key={label}>{label}</span>)}</div></div><div className="demo-answer" aria-live="polite" aria-atomic="true" aria-busy={busy}><p className="demo-question"><span>YOU</span>{answer.question}</p>{busy?<div className="demo-processing" role="status"><span/>Connecting this example journey…</div>:<div key={answer.id} className="demo-answer-content"><span className="eyebrow">PATHLY</span><h3>{answer.heading}</h3><p>{answer.body}</p><dl className="demo-stats">{answer.stats.map(s=><div key={s.label}><dt>{s.label}</dt><dd>{s.value}</dd></div>)}</dl><span className="eyebrow">NEXT TO LOOK AT</span><ol className="demo-priorities">{answer.priorities.map((p,i)=><li key={p.title}><span>0{i+1}</span><div><h4>{p.title}</h4><p>{p.detail}</p></div></li>)}</ol><a className="text-button" href="#software" onClick={()=>onExplore(answer.destination)}>Explore the example journey<ArrowUpRight size={16}/></a></div>}</div><footer>Interactive demo · Illustrative Pathly journey</footer></div></section>
}
