/** Public, authored illustration. Never import workspace records or assistant logic here. */
export const demoFacts={clinical:142,research:240,service:64,goals:3,tasksComplete:4,tasksTotal:7,programsToReview:2};
export type DemoStat={value:string;label:string};
export type DemoPriority={title:string;detail:string};
export type DemoAnswer={id:string;question:string;heading:string;body:string;context:string[];stats:DemoStat[];priorities:DemoPriority[];destination:ProductView};
export const productViews=['Experiences','Schools','Application','Goals','Journey','Ask Pathly'] as const;
export type ProductView=typeof productViews[number];
export const demoAnswers:DemoAnswer[]=[
 {id:'progress',question:'Give me a progress update',heading:'Your journey is taking shape.',body:'You’ve built experience across clinical work, research, and service. In this example journey, the next opportunity is to connect that work to your application preparation.',context:['Experiences','Goals','Schools','Application'],stats:[{value:String(demoFacts.clinical),label:'Clinical hours'},{value:String(demoFacts.research),label:'Research hours'},{value:String(demoFacts.goals),label:'Active goals'},{value:`${demoFacts.tasksComplete} / ${demoFacts.tasksTotal}`,label:'Preparation tasks complete'}],priorities:[{title:'Program requirements',detail:'Two saved programs still have unresolved items.'},{title:'Reflection',detail:'Your longest research experience does not yet have a saved reflection.'},{title:'Letter planning',detail:'One recommendation is still in progress.'}],destination:'Journey'},
 {id:'focus',question:'What should I focus on next?',heading:'Make room for the work that connects the pieces.',body:'Application planning deserves attention before adding another major activity. With three active goals and a five-hour weekly planning budget, choose one useful step at a time.',context:['Goals','Application','Schools','Capacity'],stats:[{value:'3',label:'Active priorities'},{value:'5h',label:'Weekly planning budget'}],priorities:[{title:'Review two programs',detail:'Clarify the outstanding requirements before expanding your school list.'},{title:'Preserve your research story',detail:'Capture a challenge and what you learned while the details are fresh.'}],destination:'Goals'},
 {id:'experiences',question:'How are my experiences developing?',heading:'A foundation with different kinds of perspective.',body:'Clinical work, research, and service each contribute something different. Hours show involvement; reflection helps you explain how those experiences are shaping you.',context:['Experiences','Journey','Reflections'],stats:[{value:'142',label:'Clinical hours'},{value:'240',label:'Research hours'},{value:'64',label:'Service hours'}],priorities:[{title:'Your research has depth',detail:'Turn a moment of uncertainty in the lab into a reflection about problem-solving.'},{title:'Connect service to perspective',detail:'Record what consistent involvement has taught you about listening.'}],destination:'Experiences'},
 {id:'semester',question:'What should I work on this semester?',heading:'A focused semester, not a longer checklist.',body:'Continue your existing commitments. Use a small, consistent planning window to document your experiences and address the preparation already on your plate.',context:['Goals','Schools','Application','Capacity'],stats:[{value:'3',label:'Remaining preparation tasks'},{value:'2',label:'Programs to review'}],priorities:[{title:'First: bring your records up to date',detail:'Capture the hours and meaningful details from current experiences.'},{title:'Then: review requirements',detail:'Check each saved program and note what still needs attention.'},{title:'Next: plan your letter conversation',detail:'Choose a realistic time to follow up with your recommender.'}],destination:'Application'},
 {id:'story',question:'Which experiences support my story?',heading:'Look for the moments that changed your perspective.',body:'Your clinical, research, and service experiences offer different starting points. A strong story comes from specific moments and your own reflection—not from the largest hour total.',context:['Experiences','Reflections','Story Moments','Writing'],stats:[{value:'3',label:'Experiences to revisit'},{value:'1',label:'Research reflection to capture'}],priorities:[{title:'Clinical work → communication',detail:'Recall a time you learned to listen before offering help.'},{title:'Research → curiosity',detail:'Explore how you responded when an experiment did not go as expected.'},{title:'Service → perspective',detail:'Describe what repeated involvement helped you understand.'}],destination:'Experiences'},
];
export const demoExperiences=[{title:'Clinical volunteering',category:'Clinical experience',hours:142,note:'Learning to listen, one interaction at a time.'},{title:'Undergraduate research',category:'Research',hours:240,note:'A reflection worth capturing.'},{title:'Community food program',category:'Service',hours:64,note:'Consistent involvement. A growing perspective.'}];
export const demoGoals=[{title:'Continue clinical experience',progress:'142 / 200 hours',percent:71},{title:'Review two saved programs',progress:'1 of 2 reviewed',percent:50},{title:'Capture three meaningful moments',progress:'1 of 3 captured',percent:33}];
