'use client';
import Image from 'next/image';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {Menu,X,ArrowUpRight} from 'lucide-react';
const links=[['Software','software'],['Consulting','consulting'],['How it works','how-it-works'],['About','about']];
export function MarketingBrand(){return <Link className="company-brand" href="/" aria-label="Pathly home"><span className="brand-artwork"><Image unoptimized src="/pathly-brand.png" alt="Pathly" width={2508} height={627}/></span><span className="company-tagline">Your Path, Made Clear.</span></Link>}
export function MarketingNavbar(){const [open,setOpen]=useState(false),[scrolled,setScrolled]=useState(false),toggle=useRef<HTMLButtonElement>(null);useEffect(()=>{const update=()=>setScrolled(scrollY>16);update();addEventListener('scroll',update,{passive:true});return()=>removeEventListener('scroll',update)},[]);return <header className={'marketing-nav '+(scrolled?'scrolled':'')} onKeyDown={e=>{if(e.key==='Escape'&&open){setOpen(false);toggle.current?.focus()}}}><MarketingBrand/><nav aria-label="Website navigation">{links.map(([title,id])=><a href={'/#'+id} key={id}>{title}</a>)}</nav><div className="marketing-nav-actions"><a className="marketing-open" href="/app">Open Pathly</a><a className="primary" href="/app">Start your path<ArrowUpRight size={14}/></a><button ref={toggle} className="icon-button mobile-menu-toggle" aria-label={open?'Close navigation':'Open navigation'} aria-expanded={open} aria-controls="marketing-mobile-nav" onClick={()=>setOpen(!open)}>{open?<X size={21}/>:<Menu size={21}/>}</button></div>{open&&<nav id="marketing-mobile-nav" className="marketing-mobile-nav" aria-label="Mobile website navigation">{links.map(([title,id])=><a href={'/#'+id} key={id} onClick={()=>setOpen(false)}>{title}</a>)}<a href="/app">Open Pathly</a></nav>}</header>}
export function MarketingFooter(){return <footer className="marketing-footer"><MarketingBrand/><div><p>Healthcare technology + consulting.</p><small>Technology, structured guidance, and consulting in development.</small></div><nav aria-label="Footer">{[['Software','/#software'],['Consulting','/#consulting'],['Privacy','/privacy'],['Terms','/terms'],['Help','/help'],['Open Pathly','/app']].map(([label,url])=><a key={label} href={url}>{label}</a>)}</nav></footer>}
